name: GitHub Pages Configuration

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          # Automatically detect the static site generator used
          static_site_generator: next
